# Basic configurations
spring.application.name = gym-app
spring.main.banner.mode = OFF
server.port = ${SERVER_PORT:8080}

# datasource configurations
spring.datasource.url =jdbc:postgresql://${GYM-APP_DB_HOST:localhost}:${GYM-APP_DB_PORT:5432}/${GYM-APP_DB_NAME:gym-app}
spring.datasource.username = postgres
spring.datasource.password = ${DB_PASSWORD}
spring.datasource.driver-class-name = org.postgresql.Driver

# connection pool configurations
spring.datasource.hikari.maximum-pool-size = 10
spring.datasource.hikari.minimum-idle = 2
spring.datasource.hikari.connection-time-out = 30000
spring.datasource.hikari.idle-time-out = 600000
spring.datasource.hikari.max-lifetime = 1800000

# JPA configurations
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.open-in-view = false

# liquibase configurations
spring.liquibase.enabled = false
spring.liquibase.change-log = classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema = public

# Initial administrator
app.admin.email = admin123@gmail.com
app.admin.password = admin123 

# JWT
app.jwt.secret = ${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}
app.jwt.expiration-ms = ${JWT_EXPIRATION_MS:86400000}
